#!/usr/bin/env bun
/**
 * WormDB Chat Auth Provider — mints SCT tokens for the chat demo.
 *
 * Reads the keypair from .wormdb-keys.json (generated by keygen.ts).
 *
 * Endpoints:
 *   POST /auth/login  { username: string }  →  { token: string (hex-encoded SCT) }
 *   GET  /auth/keys                         →  { publicKey: string (base64) }
 *
 * SCT binary format (matching auth.zig):
 *   [8B iat][8B exp][4B sub_len][sub][4B jti][1B cap_count][cap0][cap1]...[64B Ed25519 sig]
 *   cap = [1B op_code][1B match_type][4B pattern_len][pattern]
 *
 * The token `sub` claim = username. This is the source of truth for identity.
 */

import { readFileSync } from "fs";

// ── Load keys ──────────────────────────────────────────────────────────

const keysPath = ".wormdb-keys.json";
let keys: { publicKey: string; secretKey: string };
try {
    keys = JSON.parse(readFileSync(keysPath, "utf8"));
} catch {
    console.error(`Error: ${keysPath} not found. Run 'bun run keygen.ts --save' first.`);
    process.exit(1);
}

const secretKeyBytes = Buffer.from(keys.secretKey, "base64");
const publicKeyBytes = Buffer.from(keys.publicKey, "base64");

// Import as Web Crypto key for Ed25519 signing
// Wrap the 32-byte seed in PKCS#8 DER envelope for Ed25519
const seed = secretKeyBytes.slice(0, 32);
const pkcs8Header = new Uint8Array([
    0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05, 0x06,
    0x03, 0x2b, 0x65, 0x70, 0x04, 0x22, 0x04, 0x20,
]);
const pkcs8Key = new Uint8Array(pkcs8Header.length + seed.length);
pkcs8Key.set(pkcs8Header);
pkcs8Key.set(seed, pkcs8Header.length);

const signingKey = await crypto.subtle.importKey(
    "pkcs8",
    pkcs8Key,
    { name: "Ed25519" },
    false,
    ["sign"]
);

console.log("Auth provider loaded keypair from", keysPath);
console.log("Public key:", keys.publicKey);

// ── SCT Operations ─────────────────────────────────────────────────────

const OP = {
    GET: 0x01, SET: 0x02, DELETE: 0x03,
    SUBSCRIBE: 0x04, PUBLISH: 0x05, EXEC: 0x06, ALL: 0xff,
};

const MATCH = {
    EXACT: 0x01, PREFIX: 0x02, WILDCARD: 0xff,
};

type Capability = { op: number; match: number; pattern: string };

function chatCapabilities(): Capability[] {
    return [
        // Can execute any procedure (chat_send, chat_history, scan, etc.)
        { op: OP.EXEC, match: MATCH.WILDCARD, pattern: "" },
        // Can subscribe to chat + presence channels
        { op: OP.SUBSCRIBE, match: MATCH.PREFIX, pattern: "chat:" },
        { op: OP.SUBSCRIBE, match: MATCH.PREFIX, pattern: "presence:" },
        // Can publish to chat + presence channels
        { op: OP.PUBLISH, match: MATCH.PREFIX, pattern: "chat:" },
        { op: OP.PUBLISH, match: MATCH.PREFIX, pattern: "presence:" },
        // Can read any chat key
        { op: OP.GET, match: MATCH.PREFIX, pattern: "chat:" },
    ];
}

function benchmarkCapabilities(): Capability[] {
    return [
        // Full access for benchmark workloads
        { op: OP.ALL, match: MATCH.WILDCARD, pattern: "" },
    ];
}

async function encodeSCT(
    subject: string,
    caps: Capability[],
    ttlSeconds: number = 86400, // 24 hours
): Promise<Uint8Array> {
    const now = Math.floor(Date.now() / 1000);
    const exp = now + ttlSeconds;
    const jti = Math.floor(Math.random() * 0xffffffff);

    const subBytes = new TextEncoder().encode(subject);

    // Calculate payload size
    let payloadLen = 8 + 8 + 4 + subBytes.length + 4 + 1;
    for (const cap of caps) {
        const patBytes = new TextEncoder().encode(cap.pattern);
        payloadLen += 2 + 4 + patBytes.length;
    }

    const payload = new Uint8Array(payloadLen);
    const view = new DataView(payload.buffer);
    let pos = 0;

    // iat (8 bytes BE) — write as two 32-bit values
    view.setUint32(pos, Math.floor(now / 0x100000000), false);
    view.setUint32(pos + 4, now >>> 0, false);
    pos += 8;

    // exp (8 bytes BE)
    view.setUint32(pos, Math.floor(exp / 0x100000000), false);
    view.setUint32(pos + 4, exp >>> 0, false);
    pos += 8;

    // sub
    view.setUint32(pos, subBytes.length, false);
    pos += 4;
    payload.set(subBytes, pos);
    pos += subBytes.length;

    // jti
    view.setUint32(pos, jti, false);
    pos += 4;

    // capabilities
    payload[pos] = caps.length;
    pos += 1;

    for (const cap of caps) {
        payload[pos] = cap.op;
        payload[pos + 1] = cap.match;
        pos += 2;
        const patBytes = new TextEncoder().encode(cap.pattern);
        view.setUint32(pos, patBytes.length, false);
        pos += 4;
        payload.set(patBytes, pos);
        pos += patBytes.length;
    }

    // Sign payload with Ed25519
    const signature = new Uint8Array(await crypto.subtle.sign(
        { name: "Ed25519" },
        signingKey,
        payload,
    ));

    // Token = payload + signature
    const token = new Uint8Array(payloadLen + 64);
    token.set(payload, 0);
    token.set(signature, payloadLen);

    return token;
}

// ── HTTP Server ────────────────────────────────────────────────────────

const PORT = parseInt(process.env.AUTH_PORT || "8081");

const server = Bun.serve({
    port: PORT,
    async fetch(req) {
        const url = new URL(req.url);

        // CORS headers for browser access
        const corsHeaders = {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
            "Access-Control-Allow-Headers": "Content-Type",
        };

        if (req.method === "OPTIONS") {
            return new Response(null, { status: 204, headers: corsHeaders });
        }

        // POST /auth/login — mint a token
        if (url.pathname === "/auth/login" && req.method === "POST") {
            try {
                const body = await req.json();
                const username = body.username?.trim();
                if (!username || username.length > 32) {
                    return Response.json(
                        { error: "username required (max 32 chars)" },
                        { status: 400, headers: corsHeaders },
                    );
                }

                const scope = body.scope || "chat";
                const caps = scope === "benchmark" ? benchmarkCapabilities() : chatCapabilities();
                const token = await encodeSCT(username, caps);

                // Return as hex string (browser can convert to Uint8Array easily)
                const hex = Buffer.from(token).toString("hex");

                console.log(`[auth] Minted token for "${username}" (${caps.length} caps, expires 24h)`);

                return Response.json(
                    { token: hex, subject: username, expiresIn: 86400 },
                    { headers: corsHeaders },
                );
            } catch (err) {
                return Response.json(
                    { error: "invalid request" },
                    { status: 400, headers: corsHeaders },
                );
            }
        }

        // GET /auth/keys — public key for WormDB config
        if (url.pathname === "/auth/keys" && req.method === "GET") {
            return Response.json(
                { publicKey: keys.publicKey },
                { headers: corsHeaders },
            );
        }

        return Response.json({ error: "not found" }, { status: 404, headers: corsHeaders });
    },
});

console.log(`\n  🔐 Auth provider: http://localhost:${PORT}`);
console.log(`     POST /auth/login { username }  →  { token }`);
console.log(`     GET  /auth/keys                →  { publicKey }\n`);
